services:
  postgres:
    image: postgres:17-alpine
    container_name: ticket-webflux-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gad-dev
      POSTGRES_PASSWORD: 123456789
    volumes:
      - postgres-data-tickets:/var/lib/postgresql/data
      - ./infra/postgres/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - tickets-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gad-dev" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-keycloak:
    image: postgres:17-alpine
    container_name: keycloak-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
      POSTGRES_DB: keycloak_db
    volumes:
      - postgres-data-keycloak:/var/lib/postgresql/data
    networks:
      - tickets-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-users-ecommerce:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: ecommerce-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
    ports:
      - "8180:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - tickets-network
    depends_on:
      postgres-keycloak:
        condition: service_healthy

networks:
  tickets-network:
    driver: bridge

volumes:
  postgres-data-tickets:
  postgres-data-keycloak:
  keycloak-data: